// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXSyLWe8xE9wp7Mu2hG5hDcwLfWF_yzxo',
    appId: '1:889432922997:web:a1ddcaf45375356659513c',
    messagingSenderId: '889432922997',
    projectId: 'chat-app-flutter-surya',
    authDomain: 'chat-app-flutter-surya.firebaseapp.com',
    storageBucket: 'chat-app-flutter-surya.firebasestorage.app',
    measurementId: 'G-1FM16616XM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe0XU0PdDlavk6NwbH21y_Ff1c4V54Rh0',
    appId: '1:889432922997:ios:35d4f2d1248f82bc59513c',
    messagingSenderId: '889432922997',
    projectId: 'chat-app-flutter-surya',
    storageBucket: 'chat-app-flutter-surya.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXSyLWe8xE9wp7Mu2hG5hDcwLfWF_yzxo',
    appId: '1:889432922997:web:0e65d9d45140f48659513c',
    messagingSenderId: '889432922997',
    projectId: 'chat-app-flutter-surya',
    authDomain: 'chat-app-flutter-surya.firebaseapp.com',
    storageBucket: 'chat-app-flutter-surya.firebasestorage.app',
    measurementId: 'G-1PDF3WFNW7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe0XU0PdDlavk6NwbH21y_Ff1c4V54Rh0',
    appId: '1:889432922997:ios:35d4f2d1248f82bc59513c',
    messagingSenderId: '889432922997',
    projectId: 'chat-app-flutter-surya',
    storageBucket: 'chat-app-flutter-surya.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTsD3YVyuT24kS0pLdVDdK14odVnSbq0w',
    appId: '1:889432922997:android:39cffa9d38c2f24159513c',
    messagingSenderId: '889432922997',
    projectId: 'chat-app-flutter-surya',
    storageBucket: 'chat-app-flutter-surya.firebasestorage.app',
  );

}